[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = 'concept'
Syntax = ''
Description = 'browser driver'

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'setup'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''browser = Browser('chrome', headless=True)'''
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'open page'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'browser.visit(...)'
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'get element'
Subfeature = 'by id'
Importance = ''
"Implementation Type" = ''
Syntax = 'input_box = browser.find_by_id("legacy_text")'
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'get element'
Subfeature = 'by link text'
Importance = ''
"Implementation Type" = ''
Syntax = 'browser.find_element_by_link_text(text_id)'
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'fill text'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'input_box.fill(text)'
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'push button/ link'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'convert_button.click()'
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'get value'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'output_box.value'
Description = ''

[[data]]
Language = 'Python'
"Operand Type" = 'selenium'
Feature = 'execute javascript'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
browser.execute_script("arguments[0].click();", kaanda_element)
'''
Description = ''
