[[data]]
samUhaH = 'Commerce etc..'
software = 'https://docs.google.com/spreadsheets/d/1S8vd3QOw0CZ0H9xyblz0Fjt7q_ZV9XEAOMKTrvv8XEg/edit#gid=392850843'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'account particulars'
software = 'आर्थिक-परिस्थितिः - sheet'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'summary'
software = 'mint'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'portfolio analysis'
software = 'morningstar (IN, US)'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'US'
software = 'https://www.portfoliovisualizer.com/backtest-portfolio#analysisResults'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'Accounts / bills'
software = 'splitwise.com'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'money transfer'
software = 'venmo.com'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'
upasamUhaH = 'money transfer'
software = 'paypal.com'
"OS coverage" = 'Web'

[[data]]
samUhaH = 'Finance'

[[data]]
samUhaH = 'Task management'
upasamUhaH = 'kanban boards lists notes'
software = 'Trello'
kAraNaM = '''
1 powerup only.
 list tasks (assignable, can specify due date, can track activity), allow private boards'''

[[data]]
samUhaH = 'Task management'
upasamUhaH = 'kanban boards lists notes'
software = 'github projects'
kAraNaM = 'Good linkage with github issues. Can subscribe. Public only'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'ubuntu'
kAraNaM = 'overtaken by mint. unstable for desktops.'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'mint'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'Windows'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'Konsole'
kleshaH = 'Space before cursor problem'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'Terminal'
kleshaH = '''ctrl+tab can't be used to switch tabs'''
vyavasthA = 'Set font, set shortcuts - shift-arrows, ctrl + shift arrow, citrl t, ctrl shift t'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'nautilus'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'nautilus-open-terminal'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'nemo'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'mc'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'wine winetools'
kAraNaM = 'Running picasa and the like'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Shell'
software = 'mmv'
kAraNaM = 'mmv \*.JPG \#1.jpg'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Window management'
software = 'cinnamon'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Window management'
software = 'webilder'
kAraNaM = '''
flickr pic downloader, wallpaper rotater
obsolete in cinnamon'''

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Window management'
software = 'workspaces'
vyavasthA = 'compiz mgr "General Options > Desktop Size".'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Window management'
software = 'Ring switcher'
vyavasthA = '''
compiz mgr, dektop, unity -> free alt+tab, alt shift tab
window mgr - ring switcher - set shortcuts - enable.'''

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Window management'
software = 'System settings - shortcuts'
vyavasthA = 'Move to workspace L R U D. Move windows to workspace L R U D. Alt Tab for switching.'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Window management'
software = 'grid workspace (cinnamon applet)'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'gnome-disks / gnome-disk-utility'
kAraNaM = 'create boot-disks, format ...'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'etcher'
kAraNaM = 'create boot disks'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'gparted'
kAraNaM = 'format and modify partitions'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'fdisk'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'grub-customizer'
kAraNaM = 'grub menu modification GUI'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'Unetbootin'
kAraNaM = 'make usb boot loaders for various distributions'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'management'
software = 'webmin'
choice = 1
kAraNaM = 'web based system administration tool'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'glsof'
choice = 1
kAraNaM = 'Check on open ports'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'systemsettings kde'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'dconf editor'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'gnome-tweak-tool'
kAraNaM = 'good for configuring gnome-shell'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'hardinfo'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'apt-file'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Configuration'
software = 'qjournalctl'
choice = 1
kAraNaM = 'Good GUI for viewing journalctl (systemd) logs'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Remote access'
software = 'ssh'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Remote access'
software = 'Team viewer'
kAraNaM = 'Does not require public IP'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Remote access'
software = 'vnc'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Remote access'
software = 'nxserver nxnode'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'indicator-weather'
kleshaH = '''Can't add weather locations easily.'''

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'my-weather-indicator'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'indicator-multiload'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets cinnamon'
software = 'world clock'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets cinnamon'
software = 'weather'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets cinnamon'
software = 'multi-core system monitor'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets cinnamon'
software = 'GPU temperature'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'ClipIt'
kAraNaM = 'clipboard manager'
vyavasthA = 'limit items in history'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'glipper'
kAraNaM = 'clipboard manager'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'Parcellite'
choice = 1
kAraNaM = 'clipboard manager'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'gtk-redshift'
choice = 1
kAraNaM = 'reduce blue light at night.'
kleshaH = 'seeks config file in .config/redshift.conf'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'fcitx'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'fcitx-m17n'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Widgets'
software = 'fcitx-qt4'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'ibus'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'sanskrit'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'iBus-m17n'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'ibus-qt4'
kAraNaM = 'Needed for it to work in kde.'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'ibus-gtk3'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'm17n-db'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'm17n-contrib'
choice = 1

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'm17n repo updates'
vyavasthA = '''
git clone git://git.savannah.nongnu.org/m17n/m17n-db.git
sudo cp m17n-db/MIM/* /usr/share/m17n/
 sudo cp m17n-db/icons/* /usr/share/m17n/icons/'''

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Internationalization'
software = 'ttf-indic-fonts'
kAraNaM = 'o'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Special configuration'
software = 'Defaults        env_keep += "PATH"'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Special configuration'
software = 'pysdm'
kAraNaM = 'Disk mounting etc..'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Special configuration'
software = 'gmtp'
kAraNaM = 'Mount nexus'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Special configuration'
software = 'Unity systray whitelist'
kAraNaM = '''
gsettings get com.canonical.Unity.Panel systray-whitelist
gsettings set com.canonical.Unity.Panel systray-whitelist "['a', 'b', 'c', 'istanbul']"'''

[[data]]
samUhaH = 'OS'
upasamUhaH = '''
Special configuration
android'''
software = 'android'
kAraNaM = 'google plus upload quality'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Special configuration'
software = 'unattended-upgrades'
vyavasthA = '/etc/apt/apt.conf.d/50unattended-upgrades : enable stuff here'

[[data]]
samUhaH = 'OS'
upasamUhaH = 'Motorola atrix'
software = 'Listed elsewhere.'

[[data]]
samUhaH = 'win'
upasamUhaH = 'web'
software = 'firefox'
choice = 1

[[data]]
samUhaH = 'Internet'
upasamUhaH = 'web'
software = 'google chrome'
choice = 1

[[data]]
samUhaH = 'servers'
upasamUhaH = 'web'
software = 'tomcat'

[[data]]
samUhaH = 'servers'
upasamUhaH = 'certificate'
software = '''
certbot
certbot-systemd'''
kAraNaM = 'Valid certificates for HTTPS requests.'

[[data]]
samUhaH = 'Browsing'
software = 'xmarks'
choice = 1

[[data]]
samUhaH = 'Browsing'
software = 'lastpass'
choice = 1

[[data]]
samUhaH = 'Communication'
upasamUhaH = 'group chat'
software = 'irssi irc'

[[data]]
samUhaH = 'Communication'
upasamUhaH = 'group chat'
software = 'hexchat irc'
choice = 1

[[data]]
samUhaH = 'Communication'
upasamUhaH = 'General'
software = 'Google hangouts'
choice = 1

[[data]]
samUhaH = 'Communication'
upasamUhaH = 'group chat'
software = 'whatsapp'
choice = 1
kAraNaM = 'voice messages'

[[data]]
samUhaH = 'Communication'
upasamUhaH = 'group chat'
software = 'slack'
choice = 1
kAraNaM = 'nice add-on command-line bots for various tasks.'

[[data]]
samUhaH = 'Communication'
software = 'zoom.us'
choice = 1
kAraNaM = 'good quality, wide device coverage, screen sharing'

[[data]]
samUhaH = 'Downloading'
software = 'flashgot'
"OS coverage" = 'firefox'
kAraNaM = 'mass downloading'

[[data]]
samUhaH = 'Downloading'
software = 'bittorrent'

[[data]]
samUhaH = 'Downloading'
software = 'webhttrack'
kAraNaM = 'Download website easily.'
vyavasthA = '/usr/bin/webhttrack -> set BROWSEREXE=firefox'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'g++, gcc'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = '''
openjdk
Better: Oracle jdk'''

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'oracle jdk'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'scala'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'gfortran'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'adb, android software manager'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'Android SDK Android Studio'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Programming language'
software = 'google app engine'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Statistics'
software = 'R'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Statistics'
software = 'rapidminer'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Statistics'
software = 'rapidminer extensions'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Statistics'
software = 'weka'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'R packages'
software = 'glmnet'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'programming tools'
software = 'ipython'
choice = 1
kAraNaM = 'good python console.'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'programming tools'
software = 'kdiff3'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'IDE'
software = 'intellij idea with scala, git plugin ...'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'IDE'
software = 'eclipse'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'IDE'
software = 'eclipse-scala plugin'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'programming tools'
software = 'rstudio'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Eclipse plugins'
software = 'Python, Java, scala, C'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Eclipse plugins'
software = 'svn, egit'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Eclipse plugins'
software = 'AnyEdit'
kAraNaM = 'fix trailing spaces etc..'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'build tools'
software = 'build-essential'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'build tools'
software = 'maven'
choice = 1

[[data]]
samUhaH = 'programming'
upasamUhaH = 'Libraries'
software = 'ia32-libs'
kAraNaM = '32 bit upakaraNebhyaH Avashyakam'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'database'
software = 'sqlite3'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'database'
software = 'sqlitebrowser'

[[data]]
samUhaH = 'programming'
upasamUhaH = 'database py'
software = '''
sudo apt-get install python-dev python-pip python-setuptools build-essential
pip install csvkit'''

[[data]]
samUhaH = 'programming'
upasamUhaH = 'packaging'
software = 'packaging-dev'

[[data]]
samUhaH = 'backup/ sync'
software = 'google-drive-ocamlfuse'
"score / 5" = 0
kAraNaM = 'Use gnome account setup instead'

[[data]]
samUhaH = 'backup/ sync'
software = 'google drive chrome'
kAraNaM = 'slow'

[[data]]
samUhaH = 'backup/ sync'
software = 'dropbox'
choice = 1

[[data]]
samUhaH = 'backup/ sync'
software = 'nemo-dropbox'
choice = 1

[[data]]
samUhaH = 'backup/ sync'
upasamUhaH = 'code'
software = 'subversion'

[[data]]
samUhaH = 'backup/ sync'
upasamUhaH = 'code'
software = 'mercurial'

[[data]]
samUhaH = 'backup/ sync'
upasamUhaH = 'code'
software = 'git'
choice = 1
"score / 5" = 4.5

[[data]]
samUhaH = 'backup/ sync'
upasamUhaH = 'code'
software = 'gitk'
choice = 1

[[data]]
samUhaH = 'backup/ sync'
upasamUhaH = 'code'
software = 'git-gui'
choice = 1

[[data]]
samUhaH = 'backup/ sync'
upasamUhaH = 'code-hosting'
software = 'github'
"score / 5" = 4.5

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Tex editors'
software = 'kile'
choice = 1

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Tex editors'
software = 'texlive-latex-extra'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Tex editors'
software = 'texlive-full'
choice = 1

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Tex editors'
software = 'texmaker'

[[data]]
samUhaH = 'Editors'
software = 'kompozer'

[[data]]
samUhaH = 'Editors'
software = 'kate'
vyavasthA = 'Copy go highlighting file. Show line numbers. 2 space indentation.'

[[data]]
samUhaH = 'Editors'
software = 'jabref'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'pdf'
software = 'acroread'
choice = '??'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'pdf'
software = 'pdftk'
choice = 1
kAraNaM = 'join pdf files'
vyavasthA = 'pdftk A=one.pdf B=two.pdf cat A1-7 B1-5 A8 output combined.pdf'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'pdf'
software = 'foxit'
kAraNaM = 'good to extract text'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image'
software = 'imagemagick'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image'
software = 'gimp'
choice = 1

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image'
software = 'online websites'
kAraNaM = '''
remove background
crop to passport sizes'''

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image'
software = 'rough animator'
"OS coverage" = 'android - amazon app store'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image'
software = 'sketchbook'
vyavasthA = 'amazon app store license purchased'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image scan'
software = 'camscanner'
"OS coverage" = 'android'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'image scan'
software = 'simple-scan'
vyavasthA = 'once canon network printer was setup, it easily scanned.'

[[data]]
samUhaH = 'Editors'
software = 'kolorpaint4, digikam'

[[data]]
samUhaH = 'Editors'
software = 'go liteide'
kAraNaM = 'Go editor'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'tree / list'
software = 'checkvist'
kAraNaM = 'collapsing hoisting..'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'mind maps'
software = 'mindmup'
choice = '??'
kleshaH = 'Periodically backup as mm files - else might loose the work.'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Audio'
software = 'easytag'
choice = 1
kAraNaM = 'easy tag editing.'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Audio'
software = '''
easymp3gain, mp3diag
mp3gain'''
vyavasthA = 'mp3gain -r test01.mp3'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Audio'
software = 'lame'
choice = 1
kAraNaM = 'mp3 editing (volume boosting)'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Audio'
software = 'Audacity'
choice = 1
kAraNaM = 'volume level, amplify.'
kleshaH = '''
cant delete region while paused - must stop.
"open with audacity" crashes. Open file from within audacity.'''
vyavasthA = 'See basics tab'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Audio'
software = 'ardour'
kleshaH = 'cannot import mp3'

[[data]]
samUhaH = 'Editors'
upasamUhaH = 'Audio'
software = 'kwave'
kAraNaM = 'kde-fied audacity with simpler interface'
kleshaH = '''
set up playback and encoder separately. install lame
no fast playback. worse keyboard shortcuts.
supposedly more stable.'''

[[data]]
samUhaH = 'servers'
software = 'openssh'

[[data]]
samUhaH = 'servers'
software = 'sshfs'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'w64codecs libdvdcss2'
choice = '??'
kAraNaM = 'Medibuntu repository'
kleshaH = 'Still wont play wma and wmv - need files from gotomeeting.'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'ubuntu-restricted-extras'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'adobe flash'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'gstreamer-plugins gstreamer-plugins-ugly gstreamer-plugins-bad'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'mplayer smplayer'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'mozilla-mplayer'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'nuvola'
kAraNaM = 'grooveshark, amazon music ityAdInAm shravaNAya'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'multimedia'
software = 'sound-juicer'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = 'Dropbox-sthitAni'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = 'Music'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = 'Books'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = 'bin'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = 'app-engine config'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = '.bash*'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'Data'
software = '.ssh'

[[data]]
samUhaH = 'Data'
upasamUhaH = 'dictionary'
software = 'goldendict'
choice = 1

[[data]]
samUhaH = 'Data'
upasamUhaH = 'dictionary'
software = 'stardict-tools'
kAraNaM = 'stardict-editor converts csv files to dictionaries.'

[[data]]
samUhaH = 'Security'
software = 'AVG antivirus free'
"OS coverage" = 'Android'
kAraNaM = 'Block calls without phishing fears.'

[[data]]
samUhaH = 'Security'
upasamUhaH = 'encryption'
software = 'seahorse'
kAraNaM = 'gpg/ pgp management'

[[data]]
samUhaH = 'Security'
upasamUhaH = 'encryption, chat'
software = 'keybase'

[[data]]
samUhaH = 'Nature'
upasamUhaH = 'Sky stars'
software = 'stellarium'
choice = 1

[[data]]
samUhaH = 'Nature'
upasamUhaH = 'Sky stars'
software = 'Cartes du Ciel ("CDC" and "SkyChart")'

[[data]]
samUhaH = 'Nature'
upasamUhaH = 'Geometry, graphing'
software = 'geogebra'
choice = 1
