[[data]]
Language = 'apache '
"Operand Type" = 'run'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
sudo apache2ctl restart
sudo systemctl restart apache2.service'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'run'
Feature = 'see log'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
sudo tail -f /var/log/apache2/error.log
sudo tail -f /var/log/apache2/access.log'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'configure'
Feature = 'files'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
apache2.conf: Contains settings that are global to Apache2. Loads configs from sites-enabled etc.. below.

sites-enabled: holds symlinks to virtual host configs in /etc/apache2/sites-available
/etc/apache2/conf-available - contains available configuration files.
conf-enabled: holds symlinks to the files in /etc/apache2/conf-available. 
mods-enabled: holds symlinks to module configs in /etc/apache2/mods-available
ports.conf
'''
Description = 'configured by placing directives in plain text configuration files. These directives are separated between the following files and directories'

[[data]]
Language = 'apache '
"Operand Type" = 'configure'
Feature = 'user group'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'www-data by default'

[[data]]
Language = 'apache '
"Operand Type" = 'configure'
Feature = 'virtual host'
Subfeature = 'enable/ disable'
Importance = ''
"Implementation Type" = ''
Syntax = '''
# add /etc/apache2/sites-available/mynewsite.conf
sudo a2ensite mynewsite
sudo a2dissite mynewsite
# restart apace'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'configure'
Feature = 'module'
Subfeature = 'enable/ disable'
Importance = ''
"Implementation Type" = ''
Syntax = '''
sudo a2enmod auth_mysql
sudo a2dismod auth_mysql
# restart apache'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'config directive'
Feature = 'context'
Subfeature = ''
Importance = ''
"Implementation Type" = 'concept'
Syntax = ''
Description = 'Defines the valid contexts in which a configuration directive can appear in.'

[[data]]
Language = 'apache '
"Operand Type" = 'config directive'
Feature = 'context'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<VirtualHost>
directory - <Directory>, <Location>, <Files>, <If>, and <Proxy>
.htaccess
server config - anywhere else'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'directory config'
Feature = 'context'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'server config, virtual host'
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'directory config'
Feature = 'concept'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = '''
Defines directory resources.
If not defined within a virtual host config, applies to all virtual hosts.'''

[[data]]
Language = 'apache '
"Operand Type" = 'directory config'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<Directory "/usr/local/httpd/htdocs">
  Options Indexes FollowSymLinks
</Directory>'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'virtual host config'
Feature = 'context'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'server config'
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'virtual host config'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<VirtualHost 10.1.2.3:80>
  ServerAdmin webmaster@host.example.com
  DocumentRoot "/www/docs/host.example.com"
  ServerName host.example.com
  ErrorLog "logs/host.example.com-error_log"
  TransferLog "logs/host.example.com-access_log"
</VirtualHost>'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'basic directives'
Feature = 'domains to respond to'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
ServerName example.com
ServerAlias *.ubunturocks.com
'''
Description = 'Context:	server config, virtual host'

[[data]]
Language = 'apache '
"Operand Type" = 'basic directives'
Feature = 'contact'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'ServerAdmin xyz'
Description = 'Context:	server config, virtual host'

[[data]]
Language = 'apache '
"Operand Type" = 'virtual host config'
Feature = 'basic directives'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'DirectoryIndex ErrorDocument '
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'proxy config'
Feature = 'context'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'server config, virtual host, directory'
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'proxy config'
Feature = 'reverse'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
ProxyPass "/foo" "http://foo.example.com/bar"
ProxyPassReverse "/foo" "http://foo.example.com/bar"'''
Description = 'as far as client knows, the apache server is responding.'

[[data]]
Language = 'apache '
"Operand Type" = 'proxy config'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<Location "/mirror/foo/">
    ProxyPass "http://backend.example.com/"
</Location>'''
Description = ' local request for http://example.com/mirror/foo/bar to be internally converted into a proxy request to http://backend.example.com/bar.'

[[data]]
Language = 'apache '
"Operand Type" = 'proxy config'
Feature = 'forward'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
ProxyRequests On
ProxyVia On

<Proxy "*">
  Require host internal.example.com
</Proxy>'''
Description = 'Strictly limiting access is essential if you are using a forward proxy (using the ProxyRequests directive). Otherwise, your server can be used by any client to access arbitrary hosts while hiding his or her true identity. This is dangerous both for your network and for the Internet at large.'

[[data]]
Language = 'apache '
"Operand Type" = 'rewrite config'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = 'concept'
Syntax = ''
Description = 'mod_rewrite a flexible to manipulate URLs using an unlimited number of rules.'

[[data]]
Language = 'apache '
"Operand Type" = 'rewrite config'
Feature = ''
Subfeature = 'enable'
Importance = ''
"Implementation Type" = ''
Syntax = 'RewriteEngine on'
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'rewrite config'
Feature = ''
Subfeature = 'condition: restrict to base-path'
Importance = ''
"Implementation Type" = ''
Syntax = '    RewriteBase "/myapp/"'
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'rewrite config'
Feature = ''
Subfeature = 'condition: general'
Importance = ''
"Implementation Type" = ''
Syntax = '''
        RewriteCond %{SERVER_NAME} =api.vedavaapi.org
'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'rewrite config'
Feature = ''
Subfeature = 'force ssl'
Importance = ''
"Implementation Type" = ''
Syntax = '''
        RewriteCond %{SERVER_NAME} =api.vedavaapi.org
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
'''
Description = ''

[[data]]
Language = 'apache '
"Operand Type" = 'wsgi'
Feature = 'configure'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<VirtualHost *>
    ServerName example.com
    WSGIDaemonProcess yourapplication user=user1 group=group1 threads=5
    WSGIScriptAlias / /var/www/yourapplication/yourapplication.wsgi
   Alias /py/static /home/samskritam/vedavaapi_py_api/static
    <Directory /var/www/yourapplication>
        WSGIProcessGroup yourapplication
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>
</VirtualHost>'''
Description = 'WSGIScriptAlias points to the python code that runs.'

