[[data]]
Language = 'Google sheets'
"Operand Type" = 'add  ons'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'Use Add-ons menu'
Description = '''
Eg:  Google Sheets Power Tools
'''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'reference'
Feature = 'cell'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
sheetName!C40
sheetName!$C$40 // fixed reference
=INDIRECT("R[5]C[7]", false)'''
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'reference'
Feature = 'array'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '$P$12:$P$84'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'array'
Feature = 'literal'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '{$O$12:$O$84, $P$12:$P$84}'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'Formula'
Feature = 'scalar'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'INDIRECT("R[5]C[7]", false)'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'Formula'
Feature = 'Array'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'ARRAYFORMULA($N$12:N$84 & $O$12:$O$84)'
Description = 'result can be used as a virtual column in others.'

[[data]]
Language = 'Google sheets'
"Operand Type" = 'scalar'
Feature = 'Lookup column value by key'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'VLOOKUP(search_key, range, index, is_sorted)'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'scalar'
Feature = 'Lookup column value by key'
Subfeature = 'multiple condition columns'
Importance = ''
"Implementation Type" = ''
Syntax = '''
VLOOKUP( A1238 & B1238, 
{ARRAYFORMULA($N$12:N$84 & $O$12:$O$84), $P$12:$P$84}, 
2, FALSE)'''
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'scalar'
Feature = 'empty check'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'ISBLANK(C3)'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'array'
Feature = 'filter'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
FILTER(A2:B26, A2:A26 > 5, D2:D26 < 10)
FILTER(range, condition1, [condition2, ...])'''
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'array'
Feature = 'Conditional sum'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
SUMIF(A1:A10,">20")
SUMIF(A1:A10,"Paid",B1:B10)
SUM(FILTER(...))'''
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'array'
Feature = 'sum of product'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'SUMPRODUCT(D5:D1009="",C5:C1009,B5:B1009)'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'array'
Feature = 'count'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
count(range)
counta(range) - ignores empty cells
countif(range, ">23")
countif(range, "*xyz")'''
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'Date'
Feature = 'year'
Subfeature = 'parse'
Importance = ''
"Implementation Type" = ''
Syntax = 'year("4/8/2010")'
Description = ''

[[data]]
Language = 'Google sheets'
"Operand Type" = 'Date'
Feature = 'instantiation'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'now() today() ctrl+;'
Description = ''
