[[data]]
Language = 'web components'
"Operand Type" = 'install/ manage'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'See under js-packages.'

[[data]]
Language = 'web components'
"Operand Type" = 'use'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<!doctype html> <html>  <head>
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="bower_components/emoji-rain/emoji-rain.html">
  </head>
  <body>    <emoji-rain active></emoji-rain>  </body>
</html>'''
Description = ''

[[data]]
Language = 'web components'
"Operand Type" = 'use'
Feature = 'lazy import'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<link rel="import" href="../lazy-imports-mixin.html">
<link rel="lazy-import" href="bower_components/emoji-rain/emoji-rain.html">
'''
Description = 'Lazy import does not block web page loading. Works with Polymer'

[[data]]
Language = 'web components'
"Operand Type" = 'DOM subtree'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
const header = document.createElement('header');
const shadowRoot = header.attachShadow({mode: 'open'});
shadowRoot.innerHTML = '<h1>Hello Shadow DOM</h1>'; // Could also use appendChild().'''
Description = 'Aka shadow DOM.'

[[data]]
Language = 'web components'
"Operand Type" = 'define'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
class AppDrawer extends HTMLElement {...}
window.customElements.define('app-drawer', AppDrawer);'''
Description = ''

[[data]]
Language = 'web components'
"Operand Type" = 'define'
Feature = 'use libraries'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'bosonic polymer skatejs slim.js'

