[[data]]
Language = 'Audacity'
"Operand Type" = 'region'
Feature = 'stop and set cursor'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'x'
Description = ''

[[data]]
Language = 'Audacity'
"Operand Type" = 'region'
Feature = 'select all track-segments'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'ctrk shift k'
Description = ''

[[data]]
Language = 'Audacity'
"Operand Type" = 'track'
Feature = 'select region'
Subfeature = 'adjust'
Importance = ''
"Implementation Type" = ''
Syntax = 'ctrl (shift) left/ right  '
Description = ''

[[data]]
Language = 'Audacity'
"Operand Type" = 'track'
Feature = 'edit'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'cant delete region while paused - must stop.'

[[data]]
Language = 'Audacity'
"Operand Type" = 'track'
Feature = 'edit'
Subfeature = 'cut'
Importance = ''
"Implementation Type" = ''
Syntax = 'ctrl x'
Description = ''

[[data]]
Language = 'Audacity'
"Operand Type" = 'track'
Feature = 'import'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'drag and drop'
Description = 'cannot append to existing track.'

[[data]]
Language = 'Audacity'
"Operand Type" = 'track'
Feature = 'align to end'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'use menu'
Description = 'cannot set shortcut as of 2017'

[[data]]
Language = 'Audacity'
"Operand Type" = 'track'
Feature = 'append'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'cut and paste'
Description = 'can be done accross multiple project windows'

[[data]]
Language = 'Audacity'
"Operand Type" = 'export audio'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'use menu'
Description = 'tip: save metadata template in xml'
