addpath /public/linux/graft/matlabToolboxes/UGM
addpath /public/linux/graft/matlabToolboxes/UGM/KPM
addpath /public/linux/graft/matlabToolboxes/UGM/UGM
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/decode
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/examples
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/infer
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/mex
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/misc
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/sample
addpath /public/linux/graft/matlabToolboxes/UGM/UGM/train
addpath /public/linux/graft/matlabToolboxes/UGM/mex
addpath /public/linux/graft/matlabToolboxes/UGM/misc
addpath /u/vvasuki/vishvas/work/topology
% addpath /u/vvasuki/vishvas/work/probabilisticModels
addpath /u/vvasuki/vishvas/work/vectorSpaces
addpath /u/vvasuki/vishvas/work/optimization
addpath /u/vvasuki/vishvas/work/statistics
addpath /public/linux/graft/matlabToolboxes/PQN
addpath /public/linux/graft/matlabToolboxes/PQN/DuchiEtAl_UAI2008
addpath /public/linux/graft/matlabToolboxes/PQN/GGM
addpath /public/linux/graft/matlabToolboxes/PQN/KPM
addpath /public/linux/graft/matlabToolboxes/PQN/L1General
addpath /public/linux/graft/matlabToolboxes/PQN/L1General/sub
addpath /public/linux/graft/matlabToolboxes/PQN/UGM
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/infer
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/mex
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/potentials
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/sample
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/structures
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/sub
addpath /public/linux/graft/matlabToolboxes/PQN/UGM/train
addpath /public/linux/graft/matlabToolboxes/PQN/crfChain
addpath /public/linux/graft/matlabToolboxes/PQN/dataFiles
addpath /public/linux/graft/matlabToolboxes/PQN/expFiles
addpath /public/linux/graft/matlabToolboxes/PQN/groupL1
addpath /public/linux/graft/matlabToolboxes/PQN/lossFuncs
addpath /public/linux/graft/matlabToolboxes/PQN/minConF
addpath /public/linux/graft/matlabToolboxes/PQN/minFunc
addpath /public/linux/graft/matlabToolboxes/PQN/misc
addpath /public/linux/graft/matlabToolboxes/PQN/plotFiles
addpath /public/linux/graft/matlabToolboxes/PQN/project
addpath /public/linux/graft/matlabToolboxes/PQN/resultFiles
addpath /public/linux/graft/matlabToolboxes/lasso
addpath /public/linux/graft/matlabToolboxes/matrixIO
addpath /u/vvasuki/vishvas/work/statistics/graphl1code
addpath /public/linux/graft/matlabToolboxes/cvx
addpath /public/linux/graft/matlabToolboxes/cvx/structures
addpath /public/linux/graft/matlabToolboxes/cvx/lib
addpath /public/linux/graft/matlabToolboxes/cvx/functions
addpath /public/linux/graft/matlabToolboxes/cvx/commands
addpath /public/linux/graft/matlabToolboxes/cvx/builtins
addpath /u/vvasuki/vishvas/work/statistics/cluster
addpath /u/vvasuki/vishvas/work/statistics/cocluster/wei
addpath /u/vvasuki/vishvas/work/randomizedAlgorithms
addpath /u/vvasuki/vishvas/work/graphTheory
addpath /u/vvasuki/vishvas/work/linAlg/utilities
addpath /public/linux/graft/matlabToolboxes/randp
addpath /u/vvasuki/vishvas/work/graphTheory/graphGeneration
addpath /u/vvasuki/vishvas/progs/matlab
