[[data]]
Language = 'hugo'
"Operand Type" = 'Template variables'
Feature = 'page'
Syntax = '.Params.title'

[[data]]
Language = 'hugo'
"Operand Type" = 'Template variables'
Feature = 'site'
Syntax = '.Site.title'

[[data]]
Language = 'hugo'
"Operand Type" = 'Template variables'
Feature = 'context'
Syntax = '.scope'

[[data]]
Language = 'hugo'
"Operand Type" = 'Template variables'
Feature = 'custom'
Syntax = '$address'

[[data]]
Language = 'hugo'
"Operand Type" = 'Template variables'
Feature = 'map'
Subfeature = 'index'
Syntax = '{{ index .Params "description" }}'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'url'
Subfeature = 'relative'
Syntax = '{{ "data/pages.tsv" | relURL }}'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'loop'
Syntax = '''
{{ range .Site.Data.page_defaults }}
...
{{ end }}'''

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'conditional'
Syntax = '''
{{ if (isset .Params "description") }}
    {{ index .Params "description" }}
{{ else if (isset .Params "summary") }}
    {{ index .Params "summary" }}
{{ else }}
    {{ .Summary }}
{{ end }}'''

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'conditional'
Subfeature = 'or'
Syntax = '''
{{ if or (.Get "caption") (.Get "attribution")}}
...'''

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'print'
Syntax = 'console.debug({{.scope | jsonify}});'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'include'
Subfeature = 'cached'
Syntax = '{{ partialCached "site-footer.html" . }}'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'include'
Syntax = '{{ partial "site-footer.html" . }}'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'block'
Subfeature = 'include'
Syntax = '{{ block "footer" . }}{{ "Default stuff"}}{{ end }}'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'string'
Subfeature = 'replace regex'
Syntax = '$file_name := replaceRE "_" " " (replaceRE ".+/" "" (.Get "src"))'

[[data]]
Language = 'hugo'
"Operand Type" = 'template'
Feature = 'block'
Subfeature = 'define'
Syntax = '''
{{ define "main" }}
someHTML
{{ end }}'''

