[[data]]
"Operand Type" = 'url dispatcher'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<web-app version="2.5">
<servlet><servlet-name>trans</servlet-name>
<servlet-class>sanskritnlp.servlet.Transliterate</servlet-class>
</servlet>'''
Description = 'In file WEB-INF/web.xml'

[[data]]
"Operand Type" = 'settings'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '<appengine-web-app><application>sanskritnlp</application><version>1</version><threadsafe>true</threadsafe></appengine-web-app>'
Description = 'In file WEB-INF/appengine-web.xml'

[[data]]
"Operand Type" = 'libraries'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
Jar files in WEB-INF/lib .
Class files in WEB-INF/classes'''
Description = ''

[[data]]
"Operand Type" = 'run'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
appengine-java/bin/appcfg.sh update DIR
Or Just use maven.'''
Description = 'DIR contains WEB-INF'

[[data]]
"Operand Type" = 'maven'
Feature = 'run deployment server'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'mvn appengine:devserver'
Description = ''

[[data]]
"Operand Type" = 'maven'
Feature = 'build'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'mvn clean install'
Description = ''

[[data]]
"Operand Type" = 'maven'
Feature = 'deploy'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'appengine:update'
Description = ''

[[data]]
"Operand Type" = 'run'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
appcfg.py update DIR
'''
Description = ''

[[data]]
"Operand Type" = 'settings'
Feature = 'general'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
application: NAME
version: 1
runtime: python
api_version: 1
threadsafe: true'''
Description = 'in app.yaml'

[[data]]
"Operand Type" = 'settings'
Feature = 'main'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'main.py copied.'
Description = ''

[[data]]
"Operand Type" = 'url dispatcher'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
handlers:
- url: .*/
  static_files: vishvas/index.html
  upload: vishvas

- url: /
  static_dir: vishvas

'''
Description = 'in app.yaml'
