
[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode'
software = 'soundconverter'
choice = 1
kAraNaM = 'Transcoder - uttamam'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode'
software = 'winff libavcodec-extra'
kAraNaM = '''
transcode to audio.
multiverse package.'''

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode'
software = 'Arista'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode play'
software = 'vlc vlc-plugin-pulse mozilla-plugin-vlc'
kAraNaM = 'Good player, converter'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode'
software = 'mencoder'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode'
software = 'libfaac0'
kAraNaM = 'libfaac codec required for mpeg4 encoding'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video transcode'
software = 'libav-tools'
kAraNaM = 'ffmpeg converter.'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'video rip'
software = 'HandBrake'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video edit'
software = 'avidemux'
kAraNaM = 'Video editor, converter, volume booster'
kleshaH = 'Wont open files recorded with recordmydesktop'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video edit'
software = 'kdenlive'
kAraNaM = 'Video editor excellent.'
kleshaH = '.h264 mp4 export worked - 25 min for 1hr vid'
vyavasthA = 'Import clip. Drag it down. Move cursor using arrow. Cut clip. Delete, join. Export.'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video edit/ slideshow'
software = 'imagination'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video record (gif)'
software = 'peek'
choice = 1
kAraNaM = 'great ui, intuitive'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video record'
software = 'gtk-recordmydesktop'
kAraNaM = 'screencasting'
kleshaH = '''
Audio recording erratically stops after 4/ 15/ 15 minutes.
On the fly full screen recording of ~1920*1080 window at 15 fps and 22k audio bitrate results in picture lagging wrt the sound.'''
vyavasthA = '''
Avoided problem on ~1920*1080 window with:
8 frames per sec.
1-channel, 11K audio frequency.
Encoding on the fly. Enable subsampling.'''

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video record'
software = 'obs-studio obs-gphoto obs-qtwebkit-git'
choice = 1
kAraNaM = 'screencasting, broadcasting to YT'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video record'
software = 'guvcview'
kAraNaM = 'chalat-chitra-gRRihaNam'
kleshaH = 'mpg2 format not recognized by YT and others'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video record'
software = 'xvidcap'
kAraNaM = 'screencast'
kleshaH = 'Does not record audio'

[[data]]
samUhaH = 'Multimedia'
upasamUhaH = 'Video record'
software = 'istanbul'
kAraNaM = 'screencast'
kleshaH = '''very slow, bad ui (can't see progress after recording is stopped)'''

