[[data]]
"Operand Type" = 'concept'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'See protocol page'

[[data]]
"Operand Type" = 'XMLHttpRequest'
Feature = 'concept'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = '''
an API that provides client functionality for transferring data between a client and a server.
Despite its name, XMLHttpRequest can be used to retrieve any type of data, not just XML, and it supports protocols other than HTTP (including file and ftp).'''

[[data]]
"Operand Type" = 'XMLHttpRequest'
Feature = 'support'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = '''
Old versions of Internet Explorer (IE5 and IE6) do not support the XMLHttpRequest object.

To handle IE5 and IE6, check if the browser supports the XMLHttpRequest object, or else create an ActiveXObject:'''

[[data]]
"Operand Type" = 'XMLHttpRequest'
Feature = 'initialize'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'var xhttp = new XMLHttpRequest();'
Description = ''

[[data]]
"Operand Type" = 'XMLHttpRequest'
Feature = 'response listener'
Subfeature = 'ready state change'
Importance = ''
"Implementation Type" = ''
Syntax = '''
xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
       document.getElementById("demo").innerHTML = xhttp.responseText;
    }};'''
Description = ''

[[data]]
"Operand Type" = 'XMLHttpRequest'
Feature = 'call'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
xhttp.open("GET", "filename", true);
xhttp.send();'''
Description = ''

[[data]]
"Operand Type" = 'XMLHttpRequest'
Feature = 'properties'
Subfeature = 'read only'
Importance = ''
"Implementation Type" = ''
Syntax = '''
responseText
responseXML
status // eg. 200 for 0k, 404 for not found
statusText // text accompanying status'''
Description = ''

[[data]]
"Operand Type" = 'FormData'
Feature = 'concept'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'a way to easily construct a set of key/value pairs representing form fields and their values, which can then be easily sent using the XMLHttpRequest.send() method.'

[[data]]
"Operand Type" = 'FormData'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
fd.append(name, value);
delete(), get(), getAll(), has(), set()
'''
Description = ''

