[[data]]
"Operand Type" = 'concept'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = ''
Description = 'broad, well-tested, modular, and cross-browser JavaScript library. You can pull just what you need from a large set of reusable UI widgets and controls, and from lower-level utilities for DOM manipulation, server communication, animation, data structures, unit testing, rich-text editing, and more.'

[[data]]
"Operand Type" = 'shell html'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
<html>
  <head>
    <script src="closure-library/closure/goog/base.js"></script>
    <script src="hello.js"></script>
  </head>
  <body onload="sayHi()">
  </body>
</html>'''
Description = ''

[[data]]
"Operand Type" = 'page js'
Feature = 'structure'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
goog.require('goog.dom');

function sayHi() {
  var newHeader = goog.dom.createDom('h1', {'style': 'background-color:#EEE'},
    'Hello world!');
  goog.dom.appendChild(document.body, newHeader);
}'''
Description = ''

[[data]]
"Operand Type" = 'page js'
Feature = 'add listener'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'goog.events.listen(this.input, goog.events.EventType.KEYPRESS, function(e) { ...});'
Description = ''

[[data]]
"Operand Type" = 'page js'
Feature = 'get element'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''var parent = goog.dom.getElement('taxonomy-selection-group');'''
Description = ''
