[[data]]
Language = 'R lang'
"Operand Type" = 'variable'
Feature = 'assignment'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'fileName <- "~/stumblerRetention/retentionDataNoMissing.csv"'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'variable'
Feature = 'assignment'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'x=225+38/60+(51/60)/60'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'statement'
Feature = 'print'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'print("xia")'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'working directory'
Feature = 'set'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'setwd("../stackoverflow/")   '
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'working directory'
Feature = 'get'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'getwd()'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'table'
Feature = 'from csv'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'tblRet <- read.csv (fileName, header=TRUE, stringsAsFactors = FALSE)'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'matrix'
Feature = 'from table'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'X <- as.matrix(tblRet[,names(tblRet) != "Retained"])'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'matrix'
Feature = 'scale, center columns'
Subfeature = 'use column means, std dev'
Importance = ''
"Implementation Type" = ''
Syntax = 'X <- scale(X, center = TRUE, scale = TRUE)'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'matrix'
Feature = 'scale, center columns'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'X <- scale(X, center = 2, scale = 4)'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'vector'
Feature = 'from sequence'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
x <- seq(0, 100, length=100)
'''
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'vector'
Feature = 'normalize'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'a <- dnorm(x, mean=50, sd=1)'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'plot'
Feature = 'points'
Subfeature = 'point style'
Importance = ''
"Implementation Type" = ''
Syntax = 'points(…, pch=8, cex=1.5, col="blue", bg="red")'
Description = '''
pch: point character: 
cex: character scaling'''

[[data]]
Language = 'R lang'
"Operand Type" = 'plot'
Feature = 'points'
Subfeature = 'x,y vectors'
Importance = ''
"Implementation Type" = ''
Syntax = 'points(x, y = NULL, type = "p", …)'
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'plot'
Feature = 'points'
Subfeature = 'complex coordinates'
Importance = ''
"Implementation Type" = ''
Syntax = '''
abh=e^(1i*(tbox[j]+(x-y)*pi/180))
points(z, pch=16)'''
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'plot'
Feature = 'complex circle'
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
zcircle=e^(1i*(0:359)*pi/180)
plot(zcircle, type = "l", col="cyan4", xlim=c(-2,2), ylim = c(-2.2,2.2), asp = 1, axes = F, xlab = "", ylab = "")'''
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'plot'
Feature = 'x-y '
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = '''
plot(x, b, type="l",col=2, ylim=range(c(b,a)),)
par(new=T)
plot(x, a, type="l",col=3, ylim=range(c(b,a)), axes = FALSE, xlab = "", ylab = "")
'''
Description = ''

[[data]]
Language = 'R lang'
"Operand Type" = 'GUI rcmdr'
Feature = ''
Subfeature = ''
Importance = ''
"Implementation Type" = ''
Syntax = 'library(Rcmdr)'
Description = ''
