[[data]]
Software = 'Android studio'
"Operand Type" = 'install'
Description = 'https://g3doc.corp.google.com/engedu/abc/g3doc/exercise-1.md?cl=head'

[[data]]
Software = 'Android studio'
"Operand Type" = 'setup'
Feature = 'set up google style'
Description = '''
File > Other Settings > Default Settings
Code Style > Java
In the Scheme drop-down, select Google Configuration Checker Style.'''

[[data]]
Software = 'Android studio'
"Operand Type" = 'setup'
Feature = 'editor'
Subfeature = 'auto import'
Syntax = 'Settings > editor'
Description = 'imports will automatically be resolved when copying and pasting code'

[[data]]
Software = 'Android studio'
"Operand Type" = 'setup'
Feature = 'editor'
Subfeature = 'line numbers'

[[data]]
Software = 'Android studio'
"Operand Type" = 'Tool window'
Feature = 'Android'
Description = 'View > Tool Windows > Android'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'dev machine'
Feature = 'client and server'
Subfeature = 'concept'
Description = 'server handles communication between daemon and client.'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'dev machine'
Feature = 'server'
Subfeature = 'stop'
Syntax = 'adb kill-server && adb devices'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'dev machine'
Feature = 'server'
Subfeature = 'start'
Description = '''
run any command, like:
adb devices'''

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'dev machine'
Feature = 'devices'
Syntax = 'adb devices'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'emulator/ device'
Feature = 'daemon'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'packages'
Feature = 'install apk'
Syntax = 'adb -s localhost:9999 install -r path/to/apk/memegen_binary.apk'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'packages'
Feature = 'list'
Syntax = 'adb shell pm list packages -f'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'packages'
Feature = 'uninstall'
Syntax = 'adb uninstall com.unique.id'

[[data]]
Software = 'Android Debug Bridge (ADB)'
"Operand Type" = 'file'
Feature = 'pull'
Syntax = 'adb pull /system/app/Browser.apk /tmp/.'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'settings'
Syntax = 'file -> settings'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'settings'
Feature = 'save'
Syntax = 'file -> settings repository'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'Platform settings'
Syntax = 'right click project, open module settings'
Description = 'can set scala/ java sdk, classpath'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'Project settings'
Syntax = 'right click project, open module settings'
Description = 'Set source, path, dependencies'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'Project settings'
Feature = 'version control exclusion'
Syntax = '''Don't share workspace.xml and tasks.xml.'''

[[data]]
Software = 'intellij idea'
"Operand Type" = 'Module settings'
Syntax = 'right click project, open module settings'
Description = 'Set source, path, dependencies'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'Module settings'
Feature = 'source dir'
Subfeature = 'caveat'
Description = 'Script directories was mistaken to be a source directory, leading to compilation problems.'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'editor'
Feature = 'auto fix/ light bulb'
Syntax = '''
select or click on appropriate word. 
Or use alt-enter.'''

[[data]]
Software = 'intellij idea'
"Operand Type" = 'editor'
Feature = 'macros'
Subfeature = 'concept'
Description = 'can record, assign shortcut, invoke. very useful.'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'editor'
Feature = 'regex'
Subfeature = 'multiline'
Syntax = '\t\t\t+"[\s\S]+" rather than \t\t\t+".+"'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'Code inspection'
Syntax = 'Analyze -> Inspect code'
Description = 'Can have multiple scopes per inspection - different severity'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'git'
Syntax = 'Settings -> version control -> git -> use native client'
Description = 'else git push fails.'

[[data]]
Software = 'intellij idea'
"Operand Type" = 'sbt'
Feature = 'import module'
Description = '''Just use Intellij, and *add module with existing sources* by pointing to the build.sbt file (Don't point to the iml file: See [this thread](https://stackoverflow.com/questions/46258668/intellij-reimport-sbt-dependencies) )'''

[[data]]
Software = 'intellij idea'
"Operand Type" = 'maven'
Feature = 'import module'
Subfeature = 'setup dependencies'
Description = '''
If it complains about missing maven dependencies:
     * just open the *Maven projects* widget, refresh and do a full build.
     * Also try Maven -> reimport and *synchronoze* actions in the context menu.'''

